package com.droidlogic.setupwizardext;

import android.util.Pair;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class CountrySet {
    public static List<Pair<String, String>> countries = new ArrayList<Pair<String, String>>() {
        {
            add(new Pair("AD", "Andorra"));
            add(new Pair("AE", "United Arab Emirates"));
            add(new Pair("AF", "Afghanistan"));
            add(new Pair("AG", "Antigua & Barbuda"));
            add(new Pair("AI", "Anguilla"));
            add(new Pair("AL", "Albania"));
            add(new Pair("AM", "Armenia"));
            add(new Pair("AO", "Angola"));
            add(new Pair("AR", "Argentina"));
            add(new Pair("AS", "American Samoa"));
            add(new Pair("AT", "Austria"));
            add(new Pair("AU", "Australia"));
            add(new Pair("AW", "Aruba"));
            add(new Pair("AX", "Åland Islands"));
            add(new Pair("AZ", "Azerbaijan"));
            add(new Pair("BA", "Bosnia & Herzegovina"));
            add(new Pair("BB", "Barbados"));
            add(new Pair("BD", "Bangladesh"));
            add(new Pair("BE", "Belgium"));
            add(new Pair("BF", "Burkina Faso"));
            add(new Pair("BG", "Bulgaria"));
            add(new Pair("BH", "Bahrain"));
            add(new Pair("BI", "Burundi"));
            add(new Pair("BJ", "Benin"));
            add(new Pair("BL", "St. Barthélemy"));
            add(new Pair("BM", "Bermuda"));
            add(new Pair("BN", "Brunei"));
            add(new Pair("BO", "Bolivia"));
            add(new Pair("BQ", "Caribbean Netherlands"));
            add(new Pair("BR", "Brazil"));
            add(new Pair("BS", "Bahamas"));
            add(new Pair("BT", "Bhutan"));
            add(new Pair("BW", "Botswana"));
            add(new Pair("BY", "Belarus"));
            add(new Pair("BZ", "Belize"));
            add(new Pair("CA", "Canada"));
            add(new Pair("CC", "Cocos (Keeling)) Islands"));
            add(new Pair("CD", "Congo - Kinshasa"));
            add(new Pair("CF", "Central African Republic"));
            add(new Pair("CG", "Congo - Brazzaville"));
            add(new Pair("CH", "Switzerland"));
            add(new Pair("CI", "Côte d'Ivoire"));
            add(new Pair("CK", "Cook Islands"));
            add(new Pair("CL", "Chile"));
            add(new Pair("CM", "Cameroon"));
            add(new Pair("CN", "China"));
            add(new Pair("CO", "Colombia"));
            add(new Pair("CR", "Costa Rica"));
            add(new Pair("CU", "Cuba"));
            add(new Pair("CV", "Cape Verde"));
            add(new Pair("CW", "Curaçao"));
            add(new Pair("CX", "Christmas Island"));
            add(new Pair("CY", "Cyprus"));
            add(new Pair("CZ", "Czechia"));
            add(new Pair("DE", "Germany"));
            add(new Pair("DG", "Diego Garcia"));
            add(new Pair("DJ", "Djibouti"));
            add(new Pair("DK", "Denmark"));
            add(new Pair("DM", "Dominica"));
            add(new Pair("DO", "Dominican Republic"));
            add(new Pair("DZ", "Algeria"));
            add(new Pair("EA", "Ceuta & Melilla"));
            add(new Pair("EC", "Ecuador"));
            add(new Pair("EE", "Estonia"));
            add(new Pair("EG", "Egypt"));
            add(new Pair("EH", "Western Sahara"));
            add(new Pair("ER", "Eritrea"));
            add(new Pair("ES", "Spain"));
            add(new Pair("ET", "Ethiopia"));
            add(new Pair("FI", "Finland"));
            add(new Pair("FJ", "Fiji"));
            add(new Pair("FK", "Falkland Islands (Islas Malvinas))"));
            add(new Pair("FM", "Micronesia"));
            add(new Pair("FO", "Faroe Islands"));
            add(new Pair("FR", "France"));
            add(new Pair("GA", "Gabon"));
            add(new Pair("GB", "United Kingdom"));
            add(new Pair("GD", "Grenada"));
            add(new Pair("GE", "Georgia"));
            add(new Pair("GF", "French Guiana"));
            add(new Pair("GG", "Guernsey"));
            add(new Pair("GH", "Ghana"));
            add(new Pair("GI", "Gibraltar"));
            add(new Pair("GL", "Greenland"));
            add(new Pair("GM", "Gambia"));
            add(new Pair("GN", "Guinea"));
            add(new Pair("GP", "Guadeloupe"));
            add(new Pair("GQ", "Equatorial Guinea"));
            add(new Pair("GR", "Greece"));
            add(new Pair("GT", "Guatemala"));
            add(new Pair("GU", "Guam"));
            add(new Pair("GW", "Guinea-Bissau"));
            add(new Pair("GY", "Guyana"));
            add(new Pair("HK", "Hong Kong"));
            add(new Pair("HN", "Honduras"));
            add(new Pair("HR", "Croatia"));
            add(new Pair("HT", "Haiti"));
            add(new Pair("HU", "Hungary"));
            add(new Pair("IC", "Canary Islands"));
            add(new Pair("ID", "Indonesia"));
            add(new Pair("IE", "Ireland"));
            add(new Pair("IL", "Israel"));
            add(new Pair("IM", "Isle of Man"));
            add(new Pair("IN", "India"));
            add(new Pair("IO", "British Indian Ocean Territory"));
            add(new Pair("IQ", "Iraq"));
            add(new Pair("IR", "Iran"));
            add(new Pair("IS", "Iceland"));
            add(new Pair("IT", "Italy"));
            add(new Pair("JE", "Jersey"));
            add(new Pair("JM", "Jamaica"));
            add(new Pair("JO", "Jordan"));
            add(new Pair("JP", "Japan"));
            add(new Pair("KE", "Kenya"));
            add(new Pair("KG", "Kyrgyzstan"));
            add(new Pair("KH", "Cambodia"));
            add(new Pair("KI", "Kiribati"));
            add(new Pair("KM", "Comoros"));
            add(new Pair("KN", "St. Kitts & Nevis"));
            add(new Pair("KP", "North Korea"));
            add(new Pair("KR", "South Korea"));
            add(new Pair("KW", "Kuwait"));
            add(new Pair("KY", "Cayman Islands"));
            add(new Pair("KZ", "Kazakhstan"));
            add(new Pair("LA", "Laos"));
            add(new Pair("LB", "Lebanon"));
            add(new Pair("LC", "St. Lucia"));
            add(new Pair("LI", "Liechtenstein"));
            add(new Pair("LK", "Sri Lanka"));
            add(new Pair("LR", "Liberia"));
            add(new Pair("LS", "Lesotho"));
            add(new Pair("LT", "Lithuania"));
            add(new Pair("LU", "Luxembourg"));
            add(new Pair("LV", "Latvia"));
            add(new Pair("LY", "Libya"));
            add(new Pair("MA", "Morocco"));
            add(new Pair("MC", "Monaco"));
            add(new Pair("MD", "Moldova"));
            add(new Pair("ME", "Montenegro"));
            add(new Pair("MF", "St. Martin"));
            add(new Pair("MG", "Madagascar"));
            add(new Pair("MH", "Marshall Islands"));
            add(new Pair("MK", "Macedonia (FYROM))"));
            add(new Pair("ML", "Mali"));
            add(new Pair("MM", "Myanmar (Burma))"));
            add(new Pair("MN", "Mongolia"));
            add(new Pair("MO", "Macau"));
            add(new Pair("MP", "Northern Mariana Islands"));
            add(new Pair("MQ", "Martinique"));
            add(new Pair("MR", "Mauritania"));
            add(new Pair("MS", "Montserrat"));
            add(new Pair("MT", "Malta"));
            add(new Pair("MU", "Mauritius"));
            add(new Pair("MW", "Malawi"));
            add(new Pair("MX", "Mexico"));
            add(new Pair("MY", "Malaysia"));
            add(new Pair("MZ", "Mozambique"));
            add(new Pair("NA", "Namibia"));
            add(new Pair("NC", "New Caledonia"));
            add(new Pair("NE", "Niger"));
            add(new Pair("NF", "Norfolk Island"));
            add(new Pair("NG", "Nigeria"));
            add(new Pair("NI", "Nicaragua"));
            add(new Pair("NL", "Netherlands"));
            add(new Pair("NO", "Norway"));
            add(new Pair("NP", "Nepal"));
            add(new Pair("NR", "Nauru"));
            add(new Pair("NU", "Niue"));
            add(new Pair("NZ", "New Zealand"));
            add(new Pair("OM", "Oman"));
            add(new Pair("PA", "Panama"));
            add(new Pair("PE", "Peru"));
            add(new Pair("PF", "French Polynesia"));
            add(new Pair("PG", "Papua New Guinea"));
            add(new Pair("PH", "Philippines"));
            add(new Pair("PK", "Pakistan"));
            add(new Pair("PL", "Poland"));
            add(new Pair("PM", "St. Pierre & Miquelon"));
            add(new Pair("PN", "Pitcairn Islands"));
            add(new Pair("PR", "Puerto Rico"));
            add(new Pair("PS", "Palestine"));
            add(new Pair("PT", "Portugal"));
            add(new Pair("PW", "Palau"));
            add(new Pair("PY", "Paraguay"));
            add(new Pair("QA", "Qatar"));
            add(new Pair("RE", "Réunion"));
            add(new Pair("RO", "Romania"));
            add(new Pair("RS", "Serbia"));
            add(new Pair("RU", "Russia"));
            add(new Pair("RW", "Rwanda"));
            add(new Pair("SA", "Saudi Arabia"));
            add(new Pair("SB", "Solomon Islands"));
            add(new Pair("SC", "Seychelles"));
            add(new Pair("SD", "Sudan"));
            add(new Pair("SE", "Sweden"));
            add(new Pair("SG", "Singapore"));
            add(new Pair("SH", "St. Helena"));
            add(new Pair("SI", "Slovenia"));
            add(new Pair("SJ", "Svalbard & Jan Mayen"));
            add(new Pair("SK", "Slovakia"));
            add(new Pair("SL", "Sierra Leone"));
            add(new Pair("SM", "San Marino"));
            add(new Pair("SN", "Senegal"));
            add(new Pair("SO", "Somalia"));
            add(new Pair("SR", "Suriname"));
            add(new Pair("SS", "South Sudan"));
            add(new Pair("ST", "São Tomé & Príncipe"));
            add(new Pair("SV", "El Salvador"));
            add(new Pair("SX", "Sint Maarten"));
            add(new Pair("SY", "Syria"));
            add(new Pair("SZ", "Swaziland"));
            add(new Pair("TC", "Turks & Caicos Islands"));
            add(new Pair("TD", "Chad"));
            add(new Pair("TG", "Togo"));
            add(new Pair("TH", "Thailand"));
            add(new Pair("TJ", "Tajikistan"));
            add(new Pair("TK", "Tokelau"));
            add(new Pair("TL", "Timor-Leste"));
            add(new Pair("TM", "Turkmenistan"));
            add(new Pair("TN", "Tunisia"));
            add(new Pair("TO", "Tonga"));
            add(new Pair("TR", "Turkey"));
            add(new Pair("TT", "Trinidad & Tobago"));
            add(new Pair("TV", "Tuvalu"));
            add(new Pair("TW", "Taiwan"));
            add(new Pair("TZ", "Tanzania"));
            add(new Pair("UA", "Ukraine"));
            add(new Pair("UG", "Uganda"));
            add(new Pair("UM", "U.S. Outlying Islands"));
            add(new Pair("US", "United States"));
            add(new Pair("UY", "Uruguay"));
            add(new Pair("UZ", "Uzbekistan"));
            add(new Pair("VA", "Vatican City"));
            add(new Pair("VC", "St. Vincent & Grenadines"));
            add(new Pair("VE", "Venezuela"));
            add(new Pair("VG", "British Virgin Islands"));
            add(new Pair("VI", "U.S. Virgin Islands"));
            add(new Pair("VN", "Vietnam"));
            add(new Pair("VU", "Vanuatu"));
            add(new Pair("WF", "Wallis & Futuna"));
            add(new Pair("WS", "Samoa"));
            add(new Pair("XK", "Kosovo"));
            add(new Pair("YE", "Yemen"));
            add(new Pair("YT", "Mayotte"));
            add(new Pair("ZA", "South Africa"));
            add(new Pair("ZM", "Zambia"));
            add(new Pair("ZW", "Zimbabwe"));
            add(new Pair("ZZ", "Other"));
        }
    };
}
